export enum Endpoint {
  MAIN_PAGE = '',
  STATISTICS = 'statistics',
  CAREER = 'career',
  FEEDBACK = 'feedback',
  WIKI = 'wiki',
  PROFILE = 'profile',
  LOGIN = 'login',
  REGISTER = 'register',
  GOALS = 'goals',
  TOS = 'tos',
  PRIVACY_POLICY = 'privacy-policy',
  CAREER_PATHS = 'career-paths',
  REVIEW_PORTAL = 'review-portal',
  FINISHED_REVIEWS = 'finished-reviews',
  CAREER_LEVEL_REQUIREMENTS = 'career-level-requirements',
}
